export default [
  'A Gypsy curse.',
  'A moment of silence.',
  'A sausage festival.',
  'An honest cop with nothing left to lose.',
  'Famine.',
  'Flesh-eating bacteria.',
  'Flying sex snakes.',
  'Not giving a shit about the Third World.',
  'Sexting.',
  'Shapeshifters.',
  'Porn stars.',
  '72 virgins.',
  'A drive-by shooting.',
  'A time travel paradox.',
  'Authentic Mexican cuisine.',
  'Bling.',
  'Consultants.',
  'Crippling debt.',
  'Daddy issues.',
  'The Donald Trump Seal of Approval™.',
  'Dropping a chandelier on your enemies and riding the rope up.',
  'Former President George W. Bush.',
  'Full frontal nudity.',
  'Hormone injections.',
  'Laying an egg.',
  'Getting naked and watching Nickelodeon.',
  'Pretending to care.',
  'Public ridicule.',
  'Sharing needles.',
  'Boogers.',
  'The inevitable heat death of the universe.',
  'The miracle of childbirth.',
  'The Rapture.',
  'Whipping it out.',
  'White privilege.',
  'Wifely duties.',
  'The Hamburglar.',
  'AXE Body Spray.',
  'The Blood of Christ.',
  'Horrifying laser hair removal accidents.',
  'BATMAN!!!',
  'Agriculture.',
  'A robust mongoloid.',
  'Natural selection.',
  'Coat hanger abortions.',
  'Eating all of the cookies before the AIDS bake-sale.',
  'Michelle Obama\'s arms.',
  'The World of Warcraft.',
  'Swooping.',
  'Obesity.',
  'A homoerotic volleyball montage.',
  'Lockjaw.',
  'A mating display.',
  'Testicular torsion.',
  'All-you-can-eat shrimp for $4.99.',
  'Domino\'s™ Oreo™ Dessert Pizza.',
  'Kanye West.',
  'Hot cheese.',
  'Raptor attacks.',
  'Taking off your shirt.',
  'Smegma.',
  'Alcoholism.',
  'A middle-aged man on roller skates.',
  'The Care Bear Stare.',
  'Bingeing and purging.',
  'Oversized lollipops.',
  'Self-loathing.',
  'Children on leashes.',
  'Half-assed foreplay.',
  'The Holy Bible.',
  'German dungeon porn.',
  'Being on fire.',
  'Teenage pregnancy.',
  'Gandhi.',
  'Leaving an awkward voicemail.',
  'Uppercuts.',
  'Customer service representatives.',
  'An erection that lasts longer than four hours.',
  'My genitals.',
  'Picking up girls at the abortion clinic.',
  'Science.',
  'Not reciprocating oral sex.',
  'Flightless birds.',
  'A good sniff.',
  'Waterboarding.',
  'A balanced breakfast.',
  'Historically black colleges.',
  'Actually taking candy from a baby.',
  'The Make-A-Wish Foundation.',
  'A clandestine butt scratch.',
  'Passive-aggressive Post-it notes.',
  'The Chinese gymnastics team.',
  'Switching to Geico.',
  'Peeing a little bit.',
  'Home video of Oprah sobbing into a Lean Cuisine.',
  'Nocturnal emissions.',
  'The Jews.',
  'My humps.',
  'Powerful thighs.',
  'Winking at old people.',
  'Mr. Clean, right behind you.',
  'A gentle caress of the inner thigh.',
  'Sexual tension.',
  'The forbidden fruit.',
  'Skeletor.',
  'Fancy Feast.',
  'Being rich.',
  'Sweet, sweet vengeance.',
  'Republicans.',
  'A gassy antelope.',
  'Natalie Portman.',
  'Copping a feel.',
  'Kamikaze pilots.',
  'Sean Connery.',
  'The homosexual agenda.',
  'The hardworking Mexican.',
  'A falcon with a cap on its head.',
  'Altar boys.',
  'The Kool-Aid Man.',
  'Getting so angry that you pop a boner.',
  'Free samples.',
  'A big hoopla about nothing.',
  'Doing the right thing.',
  'The Three-Fifths compromise.',
  'Lactation.',
  'World peace.',
  'RoboCop.',
  'Chutzpah.',
  'Justin Bieber.',
  'Oompa-Loompas.',
  'Inappropriate yodeling.',
  'Puberty.',
  'Ghosts.',
  'An asymmetric boob job.',
  'Vigorous jazz hands.',
  'Fingering.',
  'Glenn Beck catching his scrotum on a curtain hook.',
  'GoGurt.',
  'Police brutality.',
  'John Wilkes Booth.',
  'Preteens.',
  'Scalping.',
  'Stifling a giggle at the mention of Hutus and Tutsis.',
  '"Tweeting."',
  'Darth Vader.',
  'A sad handjob.',
  'Exactly what you\'d expect.',
  'Expecting a burp and vomiting on the floor.',
  'Adderall™.',
  'Embryonic stem cells.',
  'Tasteful sideboob.',
  'Panda sex.',
  'An icepick lobotomy.',
  'Tom Cruise.',
  'Mouth herpes.',
  'Sperm whales.',
  'Homeless people.',
  'Third base.',
  'Incest.',
  'Pac-Man uncontrollably guzzling cum.',
  'A mime having a stroke.',
  'Hulk Hogan.',
  'God.',
  'Scrubbing under the folds.',
  'Golden showers.',
  'Emotions.',
  'Licking things to claim them as your own.',
  'Pabst Blue Ribbon.',
  'The placenta.',
  'Spontaneous human combustion.',
  'Friends with benefits.',
  'Finger painting.',
  'Old-people smell.',
  'Dying of dysentery.',
  'My inner demons.',
  'A Super Soaker™ full of cat pee.',
  'Aaron Burr.',
  'Cuddling.',
  'The chronic.',
  'Cockfights.',
  'Friendly fire.',
  'Ronald Reagan.',
  'A disappointing birthday party.',
  'A sassy black woman.',
  'Mathletes.',
  'A tiny horse.',
  'William Shatner.',
  'Riding off into the sunset.',
  'An M. Night Shyamalan plot twist.',
  'Jew-fros.',
  'Mutually-assured destruction.',
  'Pedophiles.',
  'Yeast.',
  'Grave robbing.',
  'Eating the last known bison.',
  'Catapults.',
  'Poor people.',
  'Forgetting the Alamo.',
  'The Hustle.',
  'The Force.',
  'Wiping her butt.',
  'Intelligent design.',
  'Loose lips.',
  'AIDS.',
  'Pictures of boobs.',
  'The Übermensch.',
  'Sarah Palin.',
  'American Gladiators.',
  'Getting really high.',
  'Scientology.',
  'Penis envy.',
  'Praying the gay away.',
  'Frolicking.',
  'Two midgets shitting into a bucket.',
  'The KKK.',
  'Genghis Khan.',
  'Crystal meth.',
  'Serfdom.',
  'Stranger danger.',
  'A Bop It™.',
  'Shaquille O\'Neal\'s acting career.',
  'Prancing.',
  'Vigilante justice.',
  'Overcompensation.',
  'Pixelated bukkake.',
  'A lifetime of sadness.',
  'Racism.',
  'Dwarf tossing.',
  'Sunshine and rainbows.',
  'A monkey smoking a cigar.',
  'Flash flooding.',
  'Lance Armstrong\'s missing testicle.',
  'Dry heaving.',
  'The terrorists.',
  'Britney Spears at 55.',
  'Attitude.',
  'Breaking out into song and dance.',
  'Leprosy.',
  'Gloryholes.',
  'Nipple blades.',
  'The heart of a child.',
  'Puppies!',
  'Waking up half-naked in a Denny\'s parking lot.',
  'Dental dams.',
  'Toni Morrison\'s vagina.',
  'The taint; the grundle; the fleshy fun-bridge.',
  'Active listening.',
  'Ethnic cleansing.',
  'The Little Engine That Could.',
  'The invisible hand.',
  'Waiting ‘til marriage.',
  'Unfathomable stupidity.',
  'Euphoria™ by Calvin Klein.',
  'Re-gifting.',
  'Autocannibalism.',
  'Erectile dysfunction.',
  'My collection of high-tech sex toys.',
  'The Pope.',
  'White people.',
  'Tentacle porn.',
  'Glenn Beck convulsively vomiting as a brood of crab spiders hatches in his brain and erupts from his tear ducts.',
  'Too much hair gel.',
  'Seppuku.',
  'Same-sex ice dancing.',
  'Cheating in the Special Olympics.',
  'Charisma.',
  'Keanu Reeves.',
  'Sean Penn.',
  'Nickelback.',
  'A look-see.',
  'Pooping back and forth. Forever.',
  'Menstruation.',
  'Kids with ass cancer.',
  'A salty surprise.',
  'The South.',
  'The violation of our most basic human rights.',
  'YOU MUST CONSTRUCT ADDITIONAL PYLONS.',
  'Being fabulous.',
  'Necrophilia.',
  'Centaurs.',
  'Bill Nye the Science Guy.',
  'Black people.',
  'Chivalry.',
  'Lunchables™.',
  'Bitches.',
  'The profoundly handicapped.',
  'Heartwarming orphans.',
  'MechaHitler.',
  'Fiery poops.',
  'Another goddamn vampire movie.',
  'Tangled Slinkys.',
  'The true meaning of Christmas.',
  'Estrogen.',
  'A zesty breakfast burrito.',
  'That thing that electrocutes your abs.',
  'Passing a kidney stone.',
  'A bleached asshole.',
  'Michael Jackson.',
  'Cybernetic enhancements.',
  'Guys who don\'t call.',
  'Smallpox blankets.',
  'Masturbation.',
  'Classist undertones.',
  'Queefing.',
  'Concealing a boner.',
  'Edible underpants.',
  'Viagra.',
  'Soup that is too hot.',
  'Muhammad (Praise Be Unto Him).',
  'Surprise sex!',
  'Five-Dollar Footlongs™.',
  'Drinking alone.',
  'Dick fingers.',
  'Multiple stab wounds.',
  'Soiling oneself.',
  'Child abuse.',
  'Anal beads.',
  'Civilian casualties.',
  'Pulling out.',
  'Robert Downey, Jr.',
  'Horse meat.',
  'A really cool hat.',
  'Kim Jong-il.',
  'A stray pube.',
  'Jewish fraternities.',
  'The token minority.',
  'Doin\' it in the butt.',
  'Feeding Rosie O\'Donnell.',
  'Teaching a robot to love.',
  'A can of whoop-ass.',
  'A windmill full of corpses.',
  'Count Chocula.',
  'Wearing underwear inside-out to avoid doing laundry.',
  'A death ray.',
  'The glass ceiling.',
  'A cooler full of organs.',
  'The American Dream.',
  'Keg stands.',
  'When you fart and a little bit comes out.',
  'Take-backsies.',
  'Dead babies.',
  'Foreskin.',
  'Saxophone solos.',
  'Italians.',
  'A fetus.',
  'Firing a rifle into the air while balls deep in a squealing hog.',
  'Dick Cheney.',
  'Amputees.',
  'Eugenics.',
  'My relationship status.',
  'Christopher Walken.',
  'Bees?',
  'Harry Potter erotica.',
  'College.',
  'Getting drunk on mouthwash.',
  'Nazis.',
  '8 oz. of sweet Mexican black-tar heroin.',
  'Stephen Hawking talking dirty.',
  'Dead parents.',
  'Object permanence.',
  'Opposable thumbs.',
  'Racially-biased SAT questions.',
  'Jibber-jabber.',
  'Chainsaws for hands.',
  'Nicolas Cage.',
  'Child beauty pageants.',
  'Explosions.',
  'Sniffing glue.',
  'Glenn Beck being harried by a swarm of buzzards.',
  'Repression.',
  'Roofies.',
  'My vagina.',
  'Assless chaps.',
  'A murder most foul.',
  'Giving 110 percent.',
  'Her Royal Highness, Queen Elizabeth II.',
  'The Trail of Tears.',
  'Being marginalized.',
  'Goblins.',
  'Hope.',
  'The Rev. Dr. Martin Luther King, Jr.',
  'A micropenis.',
  'My soul.',
  'A hot mess.',
  'Vikings.',
  'Hot people.',
  'Seduction.',
  'An Oedipus complex.',
  'Geese.',
  'Global warming.',
  'New Age music.',
  'Hot Pockets.',
  'Making a pouty face.',
  'Vehicular manslaughter.',
  'Women\'s suffrage.',
  'A defective condom.',
  'Judge Judy.',
  'African children.',
  'The Virginia Tech Massacre.',
  'Barack Obama.',
  'Asians who aren\'t good at math.',
  'Elderly Japanese men.',
  'Exchanging pleasantries.',
  'Heteronormativity.',
  'Parting the Red Sea.',
  'Arnold Schwarzenegger.',
  'Road head.',
  'Spectacular abs.',
  'Figgy pudding.',
  'A mopey zoo lion.',
  'A bag of magic beans.',
  'Poor life choices.',
  'My sex life.',
  'Auschwitz.',
  'A snapping turtle biting the tip of your penis.',
  'A thermonuclear detonation.',
  'The clitoris.',
  'The Big Bang.',
  'Land mines.',
  'Friends who eat all the snacks.',
  'Goats eating cans.',
  'The Dance of the Sugar Plum Fairy.',
  'Jerking off into a pool of children\'s tears.',
  'Man meat.',
  'Me time.',
  'The Underground Railroad.',
  'Poorly-timed Holocaust jokes.',
  'A sea of troubles.',
  'Lumberjack fantasies.',
  'Morgan Freeman\'s voice.',
  'Women in yogurt commercials.',
  'Natural male enhancement.',
  'Being a motherfucking sorcerer.',
  'Genital piercings.',
  'Sexy pillow fights.',
  'Balls.',
  'Grandma.',
  'Friction.',
  'Party poopers.',
  'Farting and walking away.',
  'Being a dick to children.',
  'Booby-trapping the house to foil burglars.',
  'The Tempur-Pedic Swedish Sleep System™.',
  'Dying.',
  'Hurricane Katrina.',
  'The gays.',
  'The folly of man.',
  'Men.',
  'The Amish.',
  'Pterodactyl eggs.',
  'Team-building exercises.',
  'A brain tumor.',
  'Cards Against Humanity.',
  'Fear itself.',
  'Lady Gaga.',
  'The milk man.',
  'A foul mouth.',
  'A big black dick.',
  'A beached whale.',
  'A bloody pacifier.',
  'A crappy little hand.',
  'A low standard of living.',
  'A nuanced critique.',
  'Panty raids.',
  'A passionate Latino lover.',
  'A rival dojo.',
  'A web of lies.',
  'A woman scorned.',
  'Clams.',
  'Apologizing.',
  'Appreciative snapping.',
  'Neil Patrick Harris.',
  'Beating your wives.',
  'Being a dinosaur.',
  'Shaft.',
  'Bosnian chicken farmers.',
  'Nubile slave boys.',
  'Carnies.',
  'Coughing into a vagina.',
  'Suicidal thoughts.',
  'Dancing with a broom.',
  'Deflowering the princess.',
  'Dorito breath.',
  'Eating an albino.',
  'Enormous Scandinavian women.',
  'Fabricating statistics.',
  'Finding a skeleton.',
  'Gandalf.',
  'Genetically engineered super-soldiers.',
  'George Clooney\'s musk.',
  'Getting abducted by Peter Pan.',
  'Getting in her pants, politely.',
  'Gladiatorial combat.',
  'Good grammar.',
  'Hipsters.',
  'Historical revisionism.',
  'Insatiable bloodlust.',
  'Jafar.',
  'Jean-Claude Van Damme.',
  'Just the tip.',
  'Mad hacky-sack skills.',
  'Leveling up.',
  'Literally eating shit.',
  'Making the penises kiss.',
  'Media coverage.',
  'Medieval Times Dinner and Tournament.',
  'Moral ambiguity.',
  'My machete.',
  'One thousand Slim Jims.',
  'Ominous background music.',
  'Overpowering your father.',
  'Pistol-whipping a hostage.',
  'Quiche.',
  'Quivering jowls.',
  'Revenge fucking.',
  'Ripping into a man\'s chest and pulling out his still-beating heart.',
  'Ryan Gosling riding in on a white horse.',
  'Santa Claus.',
  'Scrotum tickling.',
  'Sexual humiliation.',
  'Sexy Siamese twins.',
  'Slow motion.',
  'Space muffins.',
  'Statistically validated stereotypes.',
  'Sudden Poop Explosion Disease.',
  'The boners of the elderly.',
  'The economy.',
  'The Fanta girls.',
  'The Gulags.',
  'The harsh light of day.',
  'The hiccups.',
  'The shambling corpse of Larry King.',
  'The four arms of Vishnu.',
  'Being a busy adult with many important things to do.',
  'Tripping balls.',
  'Words, words, words.',
  'Zeus\'s sexual appetites.',
  'Weed.',
  'Doug Benson.',
  '@etchingham',
  '@Simon',
  '@sassybusdriver',
  '@DiB',
  '@buns',
  'The fattest bowl of green herb.',
  'Snoop Dogg.',
  'Stoners.',
  'The Trees Network',
  '420.',
  'My mangina.',
  'Bird up!',
  'Yah Boobay!',
  'AYY LMAO',
  'Dank memes.',
  'Jet fuel can\'t melt steel beams.',
  'Car Ramrod.',
  'A handjob from Edward Scissorhands.',
  'The Pillsbury Doughboy blowing his load all over a toaster strudel.',
  'Oompa Loompas shitting into the chocolate river.',
  'Steve Irwin dying the way he lived his life - with animals in his heart.',
  'A proctologist with poor depth perception.',
  'A Groupon for a hooker.',
  'A sex doll that just wants to be friends.',
  'All the Neopets you left forever starving but never dying.',
  'A 55-gallon drum of lube.',
  'A Burmese tiger pit.',
  'A dollop of sour cream.',
  'A fortuitous turnip harvest.',
  'A magic hippie love cloud.',
  'A man in yoga pants with a ponytail and feather earrings.',
  'A piñata full of scorpions.',
  'A sad fat dragon with no friends.',
  'A slightly shittier parallel universe.',
  'A squadron of moles wearing aviator goggles.',
  'A sweet spaceship.',
  'All of this blood.',
  'An army of skeletons.',
  'An ether-soaked rag.',
  'An unhinged ferris wheel rolling toward the sea.',
  'Another shot of morphine.',
  'Basic human decency.',
  'Beefin/’ over turf.',
  'Being awesome at sex.',
  'Boris the Soviet Love Hammer.',
  'Bullshit.',
  'Catastrophic urethral trauma.',
  'Daddy/’s belt.',
  'Death by Steven Seagal.',
  'Dennis the Menace.',
  'Double penetration.',
  'Existing.',
  'Fetal alcohol syndrome.',
  'Finding Waldo.',
  'Fuck Mountain.',
  'Getting hilariously gang-banged by the Blue Man Group.',
  'Grandpa/’s ashes.',
  'Hillary Clinton/’s death stare.',
  'Intimacy problems.',
  'Jeff Goldblum.',
  'Living in a trashcan.',
  'Making a friend.',
  'Maximal insertion.',
  'Me.',
  'Mooing.',
  'My first kill.',
  'Nunchuck moves.',
  'Oncoming traffic.',
  'One Ring to rule them all.',
  'Power.',
  'Pretty Pretty Princess Dress-Up Board Game®.',
  'Pumping out a baby every nine months.',
  'Rising from the grave.',
  'Scrotal frostbite.',
  'Some really fucked-up shit.',
  'Spring break!',
  'Subduing a grizzly bear and making her your wife.',
  'Survivor/’s guilt.',
  'Swiftly achieving orgasm.',
  'Taking a man/’s eyes and balls out and putting his eyes where his balls go and then his balls in the eye holes.',
  'The black Power Ranger.',
  'The corporations.',
  'The day the birds attacked.',
  'The Google.',
  'The grey nutrient broth that sustains Mitt Romney.',
  'The human body.',
  'The mere concept of Applebee/’s®.',
  'The mixing of the races.',
  'The new Radiohead album.',
  'Tiny nipples.',
  'Tongue.',
  'Upgrading homeless people to mobile hotspots.',
  'Weapons-grade plutonium.',
  'Wearing an octopus for a hat.',
  'Whining like a little bitch.',
  'Whipping a disobedient slave.',
  'That ass.',
  'Nothing.',
  'Shutting the fuck up.',
  'The primal, ball-slapping sex your parents are having right now.',
  'A cat video so cute that your eyes roll back and your spine slides out of your anus.',
  'Cock.',
  'A cop who is also a dog.',
  'Dying alone and in pain.',
  'Gay aliens.',
  'The way white people is.',
  'Reverse cowgirl.',
  'The Quesadilla Explosion Salad from Chili/’s.',
  'Actually getting shot, for real.',
  'Not having sex.',
  'Vietnam flashbacks.',
  'Running naked through a mall, pissing and shitting everywhere.',
  'Warm, velvety muppet sex.',
  'Self-flagellation.',
  'The systematic destruction of an entire people and their way of life.',
  'Samuel L Jackson.',
  'A boo-boo.',
  'Going around punching people.',
  'The entire Internet.',
  'Some kind of bird-man.',
  'Chugging a lava lamp.',
  'Having sex on top of a pizza.',
  'Indescribable loneliness.',
  'An ass disaster.',
  'All my friends dying.',
  'Putting an entire peanut buter and jelly sandwich into the VCR.',
  'Spending lots of money.',
  'Some douche with an acoustic guitar.',
  'Flying robots that kill people.',
  'A greased-up Matthew McConaughey.',
  'An unstoppable wave of fire ants.',
  'Not contributing to society in any meaningful way.',
  'Screaming like a maniac.',
  'The moist, demanding chasm of his mouth.',
  'Filling every orifice with butterscotch pudding.',
  'Unlimited soup, salad, and breadsticks.',
  'Crying into the pages of Sylvia Plath.',
  'Velcro.',
  'A PowerPoint presentation.',
  'A surprising amount of hair.',
  'Eating Tom Selleck/’s mustache to gain his powers.',
  'Roland the Farter, flatulist to the king.',
  'A pile of squirming bodies.',
  'Buying the right pants to be cool.',
  'Blood farts.',
  'Three months in the hole.',
  'A botched circumcision.',
  'The Land of Chocolate.',
  'Slapping a racist old lady.',
  'A lamprey swimming up the toilet and latching onto your taint.',
  'Jumping out at people.',
  'A black male in his early 20s, last seen wearing a hoodie.',
  'Mufasa/’s death scene.',
  'Bill Clinton, naked on a bearskin rug with a saxophone.',
  'Demonic possession.',
  'The Harlem Globetrotters.',
  'Vomiting mid-blowjob.',
  'My manservant, Claude.',
  'Having shotguns for legs.',
  'Letting everyone down.',
  'A spontaneous conga line.',
  'A vagina that leads to another dimension.',
  'Disco fever.',
  'Getting your dick stuck in a Chinese finger trap with another dick.',
  'Fisting.',
  'The thin veneer of situational causality that underlies porn.',
  'Girls that always be textin/’.',
  'Blowing some dudes in an alley.',
  'Drinking ten 5-hour ENERGYs to get fifty continuous hours of energy.',
  'Sneezing, farting, and coming at the same time.',
  'A bigger, blacker dick.',
  'A bunch of idiots playing a card game instead of interacting like normal humans.',
  'A sex goblin with a carnival penis.',
  'Lots and lots of abortions.',
  'Injecting speed into one arm and horse tranquilizer into the other.',
  'Sharks with legs.',
  'A sex comet from Neptune that plunges the Earth into eternal sexiness.',
  'How awesome I am.',
  'Smoking crack, for instance.',
  'A dance move that/’s just sex.',
  'A hopeless amount of spiders.',
  'Drinking responsibly.',
  'Bouncing up and down.',
  'A shiny rock that proves I love you.',
  'Crazy opium eyes.',
  'Moderate-to-severe joint pain.',
  'Actual mutants with medical conditions and no superpowers.',
  'The complex geopolitical quagmire that is the Middle East.',
  'Neil Diamond/’s Greatest Hits.',
  'No clothes on, penis in vagina.',
  'Whispering all sexy.',
  'A horse with no legs.',
  'Depression.',
  'Almost giving money to a homeless person.',
  'Interspecies marriage.',
  'Blackula.',
  'What Jesus would do.',
  'A manhole.',
  'My dad/’s dumb fucking face.',
  'A Ugandan warlord.',
  'My worthless son.',
  'A Native American who solves crimes by going into the spirit world.',
  'A kiss on the lips.',
  'A fart.',
  'The peaceful and nonthreatening rise of China.',
  'Snorting coke off a clown/’s boner.',
  'Three consecutive seconds of happiness.',
  'Falling into the toilet.',
  'Ass to mouth.',
  'Some sort of Asian.',
  'The size of my penis.',
  'The safe word.',
  'Party Mexicans.',
  'Ambiguous sarcasm.',
  'Jizz.',
  'An interracial handshake.',
  '10 Incredible Facts About the Anus.',
  'The secret formula for ultimate female satisfaction.',
  'Sugar madness.',
  'Calculating every mannerism so as not to suggest homosexuality.',
  'Fucking a corpse back to life.',
  'All the single ladies.',
  'Whatever a McRib is made of.',
  'Africa.',
  'The euphoric rush of strangling a drifter.',
  'Khakis.',
  'Stuffing a child/’s face with Fun Dip until he starts having fun.',
  'A for-real lizard that spits blood from its eyes.',
  'The tiniest shred of evidence that God is real.',
  'Prince Ali, fabulous he, Ali Ababwa.',
  'Dem titties.',
  'Exploding pigeons.',
  'My sex dungeon.',
  'Child Protective Services.',
  'Doo-doo.',
  'Sports.',
  'Unquestioning obedience.',
  'Grammar nazis who are also regular Nazis.',
  'Ejaculating live bees and the bees are angry.',
  'Free ice cream, yo.',
  'Getting caught by the police and going to jail.',
  'Getting drive-by shot.',
  'Getting eaten alive by Guy Fieri.',
  'A face full of horse cum.',
  'Too much cocaine.',
  'Blowjobs for everyone.',
  'Boring Vaginal sex.',
  'Butt stuff.',
];
